### ISSUE TITLE
使用 i3blocks，但是调整音量后刷新 i3status

### ISSUE THREAD

**Issue by jyi2ya** [vaaandark/dotfiles#1]
https://github.com/vaaandark/dotfiles/blob/b4ebe8cdb5e21b8487ffe9438eaed938b1d00e8a/i3/.config/i3/config#L74-L79

https://github.com/vaaandark/dotfiles/blob/b4ebe8cdb5e21b8487ffe9438eaed938b1d00e8a/i3/.config/i3/config#L266

**Comment by vaaandark** [comment]
Thanks, my friend! :D
